flowchart LR
    x00XORy00 -->|z00| z00
    x00ANDy00 -->|jfw| gnjANDjfw
    x00ANDy00 -->|jfw| gnjXORjfw
    x01ANDy01 -->|ntt| nttORspq
    x01XORy01 -->|gnj| gnjANDjfw
    x01XORy01 -->|gnj| gnjXORjfw
    x02ANDy02 -->|dpc| dpcORqnq
    x02XORy02 -->|jgw| jgwANDndd
    x02XORy02 -->|jgw| jgwXORndd
    x03ANDy03 -->|sqm| sqmORtvh
    x03XORy03 -->|mft| djpANDmft
    x03XORy03 -->|mft| djpXORmft
    x04ANDy04 -->|ptm| ptmORtqb
    x04XORy04 -->|vtk| npmANDvtk
    x04XORy04 -->|vtk| npmXORvtk
    x05ANDy05 -->|wkv| fnkORwkv
    x05XORy05 -->|wrk| nbkANDwrk
    x05XORy05 -->|wrk| nbkXORwrk
    x06ANDy06 -->|dhs| dhsORrvd
    x06XORy06 -->|mmh| bhdANDmmh
    x06XORy06 -->|mmh| bhdXORmmh
    x07ANDy07 -->|dqn| cptORdqn
    x07XORy07 -->|hqq| cknANDhqq
    x07XORy07 -->|hqq| cknXORhqq
    x08ANDy08 -->|pkn| pknORpmv
    x08XORy08 -->|hnf| gqsANDhnf
    x08XORy08 -->|hnf| gqsXORhnf
    x09ANDy09 -->|krd| krdORvkb
    x09XORy09 -->|tjb| tjbANDwmt
    x09XORy09 -->|tjb| tjbXORwmt
    x10ANDy10 -->|tvr| pphORtvr
    x10XORy10 -->|cmt| cdrANDcmt
    x10XORy10 -->|cmt| cdrXORcmt
    x11ANDy11 -->|scv| rcpORscv
    x11XORy11 -->|rnt| qbsANDrnt
    x11XORy11 -->|rnt| qbsXORrnt
    x12ANDy12 -->|rmg| cqbORrmg
    x12XORy12 -->|fvh| fvhANDsfk
    x12XORy12 -->|fvh| fvhXORsfk
    x13ANDy13 -->|wjj| scsORwjj
    x13XORy13 -->|cbr| cbrANDmqm
    x13XORy13 -->|cbr| cbrXORmqm
    x14ANDy14 -->|tck| sjrORtck
    x14XORy14 -->|dfb| bfnANDdfb
    x14XORy14 -->|dfb| bfnXORdfb
    x15ANDy15 -->|sbt| qtwORsbt
    x15XORy15 -->|bkb| bkbANDhbk
    x15XORy15 -->|bkb| bkbXORhbk
    x16ANDy16 -->|prt| prtORvgb
    x16XORy16 -->|chk| chkANDkfk
    x16XORy16 -->|chk| chkXORkfk
    x17ANDy17 -->|hkn| cjvORhkn
    x17XORy17 -->|kbh| jqcANDkbh
    x17XORy17 -->|kbh| jqcXORkbh
    x18XORy18 -->|grp| fgrANDgrp
    x18XORy18 -->|grp| fgrXORgrp
    x19ANDy19 -->|kkg| kkgORqvs
    x19XORy19 -->|srm| cjbANDsrm
    x19XORy19 -->|srm| cjbXORsrm
    x20ANDy20 -->|ffr| ffrORgqd
    x20XORy20 -->|nwn| nwnANDvdh
    x20XORy20 -->|nwn| nwnXORvdh
    x21ANDy21 -->|bkv| bkvORvvk
    x21XORy21 -->|cnb| cnbANDwmb
    x21XORy21 -->|cnb| cnbXORwmb
    x22ANDy22 -->|hpj| hpjORjbb
    x22XORy22 -->|bwj| bwjANDfkc
    x22XORy22 -->|bwj| bwjXORfkc
    x23ANDy23 -->|gcb| dbbORgcb
    x23XORy23 -->|rpg| dvwANDrpg
    x23XORy23 -->|rpg| dvwXORrpg
    x24ANDy24 -->|wrw| swrORwrw
    x24XORy24 -->|gjr| gjrANDrjm
    x24XORy24 -->|gjr| gjrXORrjm
    x25ANDy25 -->|gqb| dqtORgqb
    x25XORy25 -->|djd| djdANDfds
    x25XORy25 -->|djd| djdXORfds
    x26ANDy26 -->|qcp| kthORqcp
    x26XORy26 -->|fwr| bqcANDfwr
    x26XORy26 -->|fwr| bqcXORfwr
    x27ANDy27 -->|frm| frmORphq
    x27XORy27 -->|phb| hgqANDphb
    x27XORy27 -->|phb| hgqXORphb
    x28ANDy28 -->|wkc| phrORwkc
    x28XORy28 -->|hgd| hgdANDhjs
    x28XORy28 -->|hgd| hgdXORhjs
    x29ANDy29 -->|cwd| cwdORpkc
    x29XORy29 -->|dkd| dkdANDjdq
    x29XORy29 -->|dkd| dkdXORjdq
    x30ANDy30 -->|trg| trgORvbt
    x30XORy30 -->|hqs| hqsANDnhr
    x30XORy30 -->|hqs| hqsXORnhr
    x31ANDy31 -->|tpc| ghrORtpc
    x31XORy31 -->|qvq| kdhANDqvq
    x31XORy31 -->|qvq| kdhXORqvq
    x32ANDy32 -->|nbb| fdkORnbb
    x32XORy32 -->|qwt| jqmANDqwt
    x32XORy32 -->|qwt| jqmXORqwt
    x33ANDy33 -->|cht| chtORmkv
    x33XORy33 -->|gtm| gtmANDrmt
    x33XORy33 -->|gtm| gtmXORrmt
    x34ANDy34 -->|cvh| cvhANDmqf
    x34ANDy34 -->|cvh| cvhXORmqf
    x34XORy34 -->|tfn| tfnORtrj
    x35ANDy35 -->|nvg| bwdORnvg
    x35XORy35 -->|jss| cqvANDjss
    x35XORy35 -->|jss| cqvXORjss
    x36ANDy36 -->|fjf| fjfORhff
    x36XORy36 -->|dsp| bvpANDdsp
    x36XORy36 -->|dsp| bvpXORdsp
    x37ANDy37 -->|kgg| dvfORkgg
    x37XORy37 -->|bnh| bnhANDkss
    x37XORy37 -->|bnh| bnhXORkss
    x38ANDy38 -->|knq| knqORpdw
    x38XORy38 -->|bwg| bwgANDfbv
    x38XORy38 -->|bwg| bwgXORfbv
    x39ANDy39 -->|bts| btsORhjk
    x39XORy39 -->|mnm| mnmANDvhv
    x39XORy39 -->|mnm| mnmXORvhv
    x40ANDy40 -->|hdm| hdmORvkf
    x40XORy40 -->|vkn| vkgANDvkn
    x40XORy40 -->|vkn| vkgXORvkn
    x41ANDy41 -->|rnc| fhpORrnc
    x41XORy41 -->|dwh| dwhANDkqn
    x41XORy41 -->|dwh| dwhXORkqn
    x42ANDy42 -->|vvc| kcvORvvc
    x42XORy42 -->|mfm| fgvANDmfm
    x42XORy42 -->|mfm| fgvXORmfm
    x43ANDy43 -->|bvm| bvmORgsg
    x43XORy43 -->|cqm| cqmANDqqj
    x43XORy43 -->|cqm| cqmXORqqj
    x44ANDy44 -->|pfk| cjfORpfk
    x44XORy44 -->|drc| drcANDqqt
    x44XORy44 -->|drc| drcXORqqt

    bfnANDdfb -->|sjr| sjrORtck
    bfnXORdfb -->|hbk| bkbANDhbk
    bfnXORdfb -->|hbk| bkbXORhbk
    bhdANDmmh -->|rvd| dhsORrvd
    bkbANDhbk -->|qtw| qtwORsbt
    bkvORvvk -->|fkc| bwjANDfkc
    bkvORvvk -->|fkc| bwjXORfkc
    bnhANDkss -->|dvf| dvfORkgg
    bqcANDfwr -->|kth| kthORqcp
    btsORhjk -->|vkg| vkgANDvkn
    btsORhjk -->|vkg| vkgXORvkn
    bvmORgsg -->|qqt| drcANDqqt
    bvmORgsg -->|qqt| drcXORqqt
    bvpANDdsp -->|hff| fjfORhff
    bwdORnvg -->|bvp| bvpANDdsp
    bwdORnvg -->|bvp| bvpXORdsp
    bwgANDfbv -->|pdw| knqORpdw
    bwjANDfkc -->|jbb| hpjORjbb
    cbrANDmqm -->|scs| scsORwjj
    cdrANDcmt -->|pph| pphORtvr
    chkANDkfk -->|vgb| prtORvgb
    chtORmkv -->|mqf| cvhANDmqf
    chtORmkv -->|mqf| cvhXORmqf
    cjbANDsrm -->|qvs| kkgORqvs
    cjvORhkn -->|fgr| fgrANDgrp
    cjvORhkn -->|fgr| fgrXORgrp
    cknANDhqq -->|cpt| cptORdqn
    cnbANDwmb -->|vvk| bkvORvvk
    cptORdqn -->|gqs| gqsANDhnf
    cptORdqn -->|gqs| gqsXORhnf
    cqbORrmg -->|mqm| cbrANDmqm
    cqbORrmg -->|mqm| cbrXORmqm
    cqmANDqqj -->|gsg| bvmORgsg
    cqvANDjss -->|bwd| bwdORnvg
    cvhANDmqf -->|trj| tfnORtrj
    cwdORpkc -->|nhr| hqsANDnhr
    cwdORpkc -->|nhr| hqsXORnhr
    dbbORgcb -->|rjm| gjrANDrjm
    dbbORgcb -->|rjm| gjrXORrjm
    dhsORrvd -->|ckn| cknANDhqq
    dhsORrvd -->|ckn| cknXORhqq
    djdANDfds -->|dqt| dqtORgqb
    djpANDmft -->|tvh| sqmORtvh
    dkdANDjdq -->|pkc| cwdORpkc
    dpcORqnq -->|djp| djpANDmft
    dpcORqnq -->|djp| djpXORmft
    dqtORgqb -->|bqc| bqcANDfwr
    dqtORgqb -->|bqc| bqcXORfwr
    drcANDqqt -->|cjf| cjfORpfk
    dvfORkgg -->|fbv| bwgANDfbv
    dvfORkgg -->|fbv| bwgXORfbv
    dvwXORrpg -->|dbb| dbbORgcb
    dwhANDkqn -->|fhp| fhpORrnc
    fdkORnbb -->|rmt| gtmANDrmt
    fdkORnbb -->|rmt| gtmXORrmt
    ffbORkvn -->|cjb| cjbANDsrm
    ffbORkvn -->|cjb| cjbXORsrm
    ffrORgqd -->|wmb| cnbANDwmb
    ffrORgqd -->|wmb| cnbXORwmb
    fgrANDgrp -->|ffb| ffbORkvn
    fgrXORgrp -->|kvn| ffbORkvn
    fgvANDmfm -->|kcv| kcvORvvc
    fhpORrnc -->|fgv| fgvANDmfm
    fhpORrnc -->|fgv| fgvXORmfm
    fjfORhff -->|kss| bnhANDkss
    fjfORhff -->|kss| bnhXORkss
    fnkORwkv -->|bhd| bhdANDmmh
    fnkORwkv -->|bhd| bhdXORmmh
    frmORphq -->|hjs| hgdANDhjs
    frmORphq -->|hjs| hgdXORhjs
    fvhANDsfk -->|cqb| cqbORrmg
    ghrORtpc -->|jqm| jqmANDqwt
    ghrORtpc -->|jqm| jqmXORqwt
    gjrANDrjm -->|swr| swrORwrw
    gnjANDjfw -->|spq| nttORspq
    gqsANDhnf -->|pmv| pknORpmv
    gtmANDrmt -->|mkv| chtORmkv
    hdmORvkf -->|kqn| dwhANDkqn
    hdmORvkf -->|kqn| dwhXORkqn
    hgdANDhjs -->|phr| phrORwkc
    hgqANDphb -->|phq| frmORphq
    hpjORjbb -->|dvw| dvwANDrpg
    hpjORjbb -->|dvw| dvwXORrpg
    hqsANDnhr -->|vbt| trgORvbt
    jgwANDndd -->|qnq| dpcORqnq
    jqcANDkbh -->|cjv| cjvORhkn
    jqmANDqwt -->|fdk| fdkORnbb
    kcvORvvc -->|qqj| cqmANDqqj
    kcvORvvc -->|qqj| cqmXORqqj
    kdhANDqvq -->|ghr| ghrORtpc
    kkgORqvs -->|vdh| nwnANDvdh
    kkgORqvs -->|vdh| nwnXORvdh
    knqORpdw -->|vhv| mnmANDvhv
    knqORpdw -->|vhv| mnmXORvhv
    krdORvkb -->|cdr| cdrANDcmt
    krdORvkb -->|cdr| cdrXORcmt
    kthORqcp -->|hgq| hgqANDphb
    kthORqcp -->|hgq| hgqXORphb
    mnmANDvhv -->|hjk| btsORhjk
    nbkANDwrk -->|fnk| fnkORwkv
    npmANDvtk -->|tqb| ptmORtqb
    nttORspq -->|ndd| jgwANDndd
    nttORspq -->|ndd| jgwXORndd
    nwnANDvdh -->|gqd| ffrORgqd
    phrORwkc -->|jdq| dkdANDjdq
    phrORwkc -->|jdq| dkdXORjdq
    pknORpmv -->|wmt| tjbANDwmt
    pknORpmv -->|wmt| tjbXORwmt
    pphORtvr -->|qbs| qbsANDrnt
    pphORtvr -->|qbs| qbsXORrnt
    prtORvgb -->|jqc| jqcANDkbh
    prtORvgb -->|jqc| jqcXORkbh
    ptmORtqb -->|nbk| nbkANDwrk
    ptmORtqb -->|nbk| nbkXORwrk
    qbsANDrnt -->|rcp| rcpORscv
    qtwORsbt -->|kfk| chkANDkfk
    qtwORsbt -->|kfk| chkXORkfk
    rcpORscv -->|sfk| fvhANDsfk
    rcpORscv -->|sfk| fvhXORsfk
    scsORwjj -->|bfn| bfnANDdfb
    scsORwjj -->|bfn| bfnXORdfb
    sqmORtvh -->|npm| npmANDvtk
    sqmORtvh -->|npm| npmXORvtk
    swrORwrw -->|fds| djdANDfds
    swrORwrw -->|fds| djdXORfds
    tfnORtrj -->|cqv| cqvANDjss
    tfnORtrj -->|cqv| cqvXORjss
    tjbANDwmt -->|vkb| krdORvkb
    trgORvbt -->|kdh| kdhANDqvq
    trgORvbt -->|kdh| kdhXORqvq
    vkgANDvkn -->|vkf| hdmORvkf

    gnjXORjfw -->|z01| z01
    jgwXORndd -->|z02| z02
    djpXORmft -->|z03| z03
    npmXORvtk -->|z04| z04
    nbkXORwrk -->|z05| z05
    bhdXORmmh -->|z06| z06
    cknXORhqq -->|z07| z07
    gqsXORhnf -->|z08| z08
    tjbXORwmt -->|z09| z09
    cdrXORcmt -->|z10| z10
    qbsXORrnt -->|z11| z11
    fvhXORsfk -->|z12| z12
    cbrXORmqm -->|z13| z13
    sjrORtck -->|z14| z14
    bkbXORhbk -->|z15| z15
    chkXORkfk -->|z16| z16
    jqcXORkbh -->|z17| z17
    x18ANDy18 -->|z18| z18
    cjbXORsrm -->|z19| z19
    nwnXORvdh -->|z20| z20
    cnbXORwmb -->|z21| z21
    bwjXORfkc -->|z22| z22
    dvwANDrpg -->|z23| z23
    gjrXORrjm -->|z24| z24
    djdXORfds -->|z25| z25
    bqcXORfwr -->|z26| z26
    hgqXORphb -->|z27| z27
    hgdXORhjs -->|z28| z28
    dkdXORjdq -->|z29| z29
    hqsXORnhr -->|z30| z30
    kdhXORqvq -->|z31| z31
    jqmXORqwt -->|z32| z32
    gtmXORrmt -->|z33| z33
    cvhXORmqf -->|z34| z34
    cqvXORjss -->|z35| z35
    bvpXORdsp -->|z36| z36
    bnhXORkss -->|z37| z37
    bwgXORfbv -->|z38| z38
    mnmXORvhv -->|z39| z39
    vkgXORvkn -->|z40| z40
    dwhXORkqn -->|z41| z41
    fgvXORmfm -->|z42| z42
    cqmXORqqj -->|z43| z43
    drcXORqqt -->|z44| z44
    cjfORpfk -->|z45| z45